# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import filter_pb2 as filter__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in filter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilterAgentStub(object):
    """Services //
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/com.tbsen.proto.FilterAgent/RegisterAgent',
                request_serializer=filter__pb2.AgentIdentity.SerializeToString,
                response_deserializer=filter__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ReportStatus = channel.stream_unary(
                '/com.tbsen.proto.FilterAgent/ReportStatus',
                request_serializer=filter__pb2.AgentStatus.SerializeToString,
                response_deserializer=filter__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SubscribeCommands = channel.unary_stream(
                '/com.tbsen.proto.FilterAgent/SubscribeCommands',
                request_serializer=filter__pb2.AgentIdentity.SerializeToString,
                response_deserializer=filter__pb2.Command.FromString,
                _registered_method=True)
        self.ReportCommandResult = channel.unary_unary(
                '/com.tbsen.proto.FilterAgent/ReportCommandResult',
                request_serializer=filter__pb2.CommandResponse.SerializeToString,
                response_deserializer=filter__pb2.CommandResponse.FromString,
                _registered_method=True)


class FilterAgentServicer(object):
    """Services //
    """

    def RegisterAgent(self, request, context):
        """등록 (에이전트 -> 서버)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStatus(self, request_iterator, context):
        """상태보고 (에이전트 -> 서버)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeCommands(self, request, context):
        """명령 수신 (서버 -> 에이전트)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCommandResult(self, request, context):
        """명령 결과 보고 (에이전트 -> 서버)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilterAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=filter__pb2.AgentIdentity.FromString,
                    response_serializer=filter__pb2.CommandResponse.SerializeToString,
            ),
            'ReportStatus': grpc.stream_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=filter__pb2.AgentStatus.FromString,
                    response_serializer=filter__pb2.CommandResponse.SerializeToString,
            ),
            'SubscribeCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeCommands,
                    request_deserializer=filter__pb2.AgentIdentity.FromString,
                    response_serializer=filter__pb2.Command.SerializeToString,
            ),
            'ReportCommandResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCommandResult,
                    request_deserializer=filter__pb2.CommandResponse.FromString,
                    response_serializer=filter__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.tbsen.proto.FilterAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.tbsen.proto.FilterAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilterAgent(object):
    """Services //
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.tbsen.proto.FilterAgent/RegisterAgent',
            filter__pb2.AgentIdentity.SerializeToString,
            filter__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStatus(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.tbsen.proto.FilterAgent/ReportStatus',
            filter__pb2.AgentStatus.SerializeToString,
            filter__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.tbsen.proto.FilterAgent/SubscribeCommands',
            filter__pb2.AgentIdentity.SerializeToString,
            filter__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCommandResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.tbsen.proto.FilterAgent/ReportCommandResult',
            filter__pb2.CommandResponse.SerializeToString,
            filter__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
